### ISSUE TITLE
Sample crash while running under WSL-2 + Brew

### ISSUE THREAD

**Issue by Nordes** [fluxcd/source-watcher#16]
I wanted to try building a new components, but first I tried the demo (source-watcher). I did what was in the requirements:

- flux (latest already installed)
- docker (latest already installed)
- brew install go (go version go1.16.2 linux/amd64)
- brew install kind 
- brew install kustomize
- brew install kubectl
- brew install kubebuilder

Issue hit `#1` When running the `make`:
```bash
 ~/git/github/flux/source-watcher                                                                                                                                                            09:58:33  north-pole
❯ make
go: creating new go.mod: module tmp
go get: added sigs.k8s.io/controller-tools v0.3.0
/home/nordes/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/home/linuxbrew/.linuxbrew/Cellar/go/1.16.2_1/libexec/src/net/cgo_linux.go:12:8: no such package located
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [Makefile:55: generate] Error 1
```

To fix, I did : `CGO_ENABLED=0 make` and it passed

Then I ran `CGO_ENABLED=0 make run` so that it starts. First logs seems fine but when I create the GitRepository I have the following:
```bash
E0320 10:09:14.243913   33083 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 292 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15538c0, 0x22103b0)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x15538c0, 0x22103b0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.16.2_1/libexec/src/runtime/panic.go:965 +0x1b9
github.com/fluxcd/source-watcher/controllers.(*GitRepositoryWatcher).Reconcile(0xc000892750, 0x18dcca8, 0xc000b43890, 0xc000041ae0, 0xb, 0xc000041ad0, 0x4, 0xc000b43800, 0x0, 0x0, ...)
        /home/nordes/git/github/flux/source-watcher/controllers/gitrepository_watcher.go:55 +0x25c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002bda40, 0x18dcc00, 0xc0005acb80, 0x159dbc0, 0xc0007933a0)
        /home/nordes/git/github/flux/source-watcher/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002bda40, 0x18dcc00, 0xc0005acb80, 0x0)
        /home/nordes/git/github/flux/source-watcher/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x18dcc00, 0xc0005acb80)
        /home/nordes/git/github/flux/source-watcher/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000b07750)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000b37f50, 0x18ae280, 0xc000892a50, 0xc0005acb01, 0xc000045860)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b07750, 0x3b9aca00, 0x0, 0x1, 0xc000045860)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x18dcc00, 0xc0005acb80, 0xc00037fd10, 0x3b9aca00, 0x0, 0x1)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x18dcc00, 0xc0005acb80, 0xc00037fd10, 0x3b9aca00)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /home/nordes/git/github/flux/source-watcher/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213 +0x40d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x144ba7c]

goroutine 292 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x15538c0, 0x22103b0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.16.2_1/libexec/src/runtime/panic.go:965 +0x1b9
github.com/fluxcd/source-watcher/controllers.(*GitRepositoryWatcher).Reconcile(0xc000892750, 0x18dcca8, 0xc000b43890, 0xc000041ae0, 0xb, 0xc000041ad0, 0x4, 0xc000b43800, 0x0, 0x0, ...)
        /home/nordes/git/github/flux/source-watcher/controllers/gitrepository_watcher.go:55 +0x25c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002bda40, 0x18dcc00, 0xc0005acb80, 0x159dbc0, 0xc0007933a0)
        /home/nordes/git/github/flux/source-watcher/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002bda40, 0x18dcc00, 0xc0005acb80, 0x0)
        /home/nordes/git/github/flux/source-watcher/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x18dcc00, 0xc0005acb80)
        /home/nordes/git/github/flux/source-watcher/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000b07750)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000b37f50, 0x18ae280, 0xc000892a50, 0xc0005acb01, 0xc000045860)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b07750, 0x3b9aca00, 0x0, 0x1, 0xc000045860)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x18dcc00, 0xc0005acb80, 0xc00037fd10, 0x3b9aca00, 0x0, 0x1)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x18dcc00, 0xc0005acb80, 0xc00037fd10, 0x3b9aca00)
        /home/nordes/git/github/flux/source-watcher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /home/nordes/git/github/flux/source-watcher/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213 +0x40d
exit status 2
make: *** [Makefile:26: run] Error 1
```

Any ideas what's happening? I remember not having any issues in WSL-2 with go in the past.

**Comment by Nordes** [comment]
By looking at the `Makefile`, I decided to run directly `go run ./main.go` and it worked. So, I guess there's an issue at the beginning of the `Makefile`.

```
# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif
```

**Comment by Nordes** [comment]
Current fix, stupid enough, simply uninstall the brew version and then install GO as the official site says. Make now works as expected.

**Comment by Nordes** [comment]
@stefanprodan I found out that the nil exception was due to something else. I fixed it in my fork branch. This was due to the Create event that was trying to run the reconcile method without having an artifact. 

**2 options for the fix:** 
1. Add an if to look if the artifact is existing (not nil)
2. Bind the hook in the `gitrepository_predicate.go`

**Option 1** (`gitrepository_watcher.go`)
```go
        // existing code...

	// This if is necessary if you don't bind the Create event
	if repository.Status.Artifact == nil {
		// No artifact, can happen on creation of GitRepository, not yet ready to reconciler. Update event will happen for that.
		return ctrl.Result{}, nil
	}

	log.Info("New revision detected", "revision", repository.Status.Artifact.Revision)
        // existing code...
```

**Option 2** (`gitrepository_predicate.go`)
```go
//... existing code

func (GitRepositoryRevisionChangePredicate) Create(e event.CreateEvent) bool {
	src, ok := e.Object.(sourcev1.Source)

	// Skip if not able to fetch the artifact
	if !ok || src.GetArtifact() == nil {
		return false
	}

	return true
}

func (GitRepositoryRevisionChangePredicate) Delete(e event.DeleteEvent) bool {
	// Skip deletion
	return false
}

func (GitRepositoryRevisionChangePredicate) Update(e event.UpdateEvent) bool {
//... existing code
```

As my knowledge of GO is pretty much "low", I didn't do a PR. But it's still worth mentioning.

**Comment by stefanprodan** [comment]
@Nordes I think you are running an older version, the predicate has safeguards in place https://github.com/fluxcd/source-watcher/blob/main/controllers/gitrepository_predicate.go

**Comment by Nordes** [comment]
I forked/cloned again this Saturday (different pc), so I guess the version is the same. I can retry later this evening.

**Comment by stefanprodan** [comment]
@Nordes as you can see there is no `func (GitRepositoryRevisionChangePredicate) Delete(e event.DeleteEvent)` in main.

**Comment by Nordes** [comment]
Yes, I know, I added it for later use, but regarding the `func (GitRepositoryRevisionChangePredicate) Create(e event.CreateEvent) bool {`, I needed to add that block. Otherwise it was crashing in the watcher (exactly at: https://github.com/fluxcd/source-watcher/blob/main/controllers/gitrepository_watcher.go#L55 ).

**Comment by stefanprodan** [comment]
This should prevent repos with nil artifacts from reaching the reconciler https://github.com/fluxcd/source-watcher/blob/main/controllers/gitrepository_predicate.go#L51

**Comment by Nordes** [comment]
The `Create` went directly into the watcher before going into the Update. Maybe my `go` went a bit wrong after building (somehow). As I've mentioned I'll try again later this evening and confirms back here.

**Comment by stefanprodan** [comment]
Well there is no create command in this repo....

**Comment by Nordes** [comment]
I know, but the hook still triggers and goes into the watcher code and make the application crashing. Don`t ask me why. Maybe the default behavior of the create is to return "true"? I don't know.

In between two calls this morning, I've reinstalled everything and followed https://toolkit.fluxcd.io/dev-guides/source-watcher/ (clone and all) and then at the creation of the source:
```
flux create source git test \
--url=https://github.com/stefanprodan/podinfo \
--tag=4.0.0
```

**It still "crash".** 

Install:
![image](https://user-images.githubusercontent.com/446572/111996884-d8433780-8af0-11eb-8057-c198c8a40e3e.png)

Create the source
![image](https://user-images.githubusercontent.com/446572/111997029-00329b00-8af1-11eb-9f6f-5e73fa1c4003.png)

Startup + Crash after creation of the source:
![image](https://user-images.githubusercontent.com/446572/111996967-ed1fcb00-8af0-11eb-95a9-73ec8d76ba21.png)

**Comment by stefanprodan** [comment]
Oh maybe the default behavior changed after the latest controller-runtime update. It makes sense to add a safeguard in the reconciler

**Comment by stefanprodan** [comment]
If you want to PR please do, if not I’ll fix it, let me know please and thanks for reporting this.
